### PR TITLE
Add more variables to electron and photon value maps

### PR DESCRIPTION
**Pull request by artlbv**

### CODE REVIEW

**Comment by artlbv** [comment]
@beaudett, @nsmith- , @jkiesele please verify all required variables are present now.
I believe that especially for photons there might be something to add, e.g. the track veto.

**Comment by nsmith-** [comment]
I don't see the reason for saving variables that already exist or can be derived from the object members itself.
Can we just store the values that cannot be computed without working with the RecHits?

**Comment by jkiesele** [comment]
I fully agree with Nick.
We should only safe those variables that are not anyway available in miniAOD. Anything else will also not make it through the CMSSW PR.

**Comment by artlbv** [comment]
I thought we put all the ID variables in these value maps, but if not, then they surely can be omitted.
Will then there be an additional step where all variables will be collected?

**Comment by nsmith-** [comment]
Yeah, when making the pat object, we'll stuff all these ValueMaps into it as userFloats.

**Comment by nsmith-** [comment]
@artlbv can you merge this for now?  I need to make a change to the way the valuemap producer works to ease integration in miniaod.

**Pull request merged**
